### ISSUE TITLE
您好，您提供的项目代码不全，可以问您要一下吗？

### ISSUE THREAD

**Issue by Dwade-Sam** [fduxuan/SDM-Attack#2]
目前，想复现您的代码，但是遇到了问题，所以想问您要一下：-counter_fitting_embeddings_path data/counter-fitted-vectors.txt       --counter_fitting_cos_sim_path data/cos_sim_counter_fitting.npy

**Comment by fduxuan** [comment]
参考 [TextFooler](https://github.com/jind11/TextFooler).

**Comment by Dwade-Sam** [comment]
好的感谢
